---
title: "Graph 4 Tweet"
author: "Lingyun Wang, 3940"
date: "4/4/2021"
output: html_document
---

```{r setup, include=FALSE}
library(sf)
library(tidyverse)
library(ggthemes)
library(extrafont)
library(waffle)
library(hrbrthemes)
library(ggplot2)
library(rgeos)
library(plotly)
library(viridis)
library(leaflet)
library(showtext)

extrafont::font_import (path="/Users/lucywang/Downloads", pattern = "fa-", prompt =  FALSE)

loadfonts()

font_add(family = "FontAwesome5Free-Solid", regular = "/Users/lucywang/Downloads/fa-solid-900.ttf")
font_add(family = "FontAwesome5Free-Regular", regular = "/Users/lucywang/Downloads/fa-regular-400.ttf")
font_add(family = "FontAwesome5Brands-Regular", regular = "/Users/lucywang/Downloads/fa-brands-400.ttf")
showtext_auto()
```


```{r}
graph4 <-read.csv("/Users/lucywang/StudioProjects/STA313-FINAL-PROJECT/data/twitter_sentiment_data.csv")


graph4 <- graph4%>%select(-c(tweetid, message))%>%
  group_by(sentiment)%>%
  count()%>%
  mutate(graph_n=round(as.numeric(n)/1000,0))%>%
  mutate(percentage=round(n/43943*100,1))%>%
  mutate(sentiment = case_when(sentiment == -1 ~ "Anti(-1)",
                               sentiment == 0 ~ "Neutral(0)",
                               sentiment == 1 ~ "Pro(1)",
                               sentiment == 2 ~"News(2)"))%>%
  mutate(text = paste("Neighbourhood: ", sentiment, "\nTotal Case Count: ", n, sep=""))
  
graph4

waffleee <- c(`anti(-1)` =3990, `neutral(0)` = 7715,
              `pro(1)`=22962, `news(2)` = 9276)

```



```{r}
birdwaffle<-waffle(#graph4$sentiment = graph4$graph_n,
  c(`anti(-1)` = 4, `neutral(0)` = 8,`pro(1)`=23, `news(2)` = 9), 
  rows = 4, colors=c("tomato", "palegreen", "skyblue", "plum1"),
  use_glyph = "twitter", 
  glyph_size = 7, 
  glyph_font = "Font Awesome 5 Brands Regular",
  glyph_font_family = "FontAwesome5Brands-Regular",
  title = "Is Climate Change Man-Made? \nResponses on Twitter",
  legend_pos="top") +
  theme(plot.title = element_text(size=12, face="bold", hjust = 0.5, vjust=0))+
  coord_equal() +
  #theme_enhance_waffle() +
  theme(legend.text = element_text(size = 8, vjust = 0.5))

birdwaffle
```
```{r}
#ggplotly(birdwaffle)
  
```



```{r}

waffle(waffleee/1000, rows=5,  
       colors=c("#44D2AC", "#E48B8B", "#B67093", 
                "#3A9ABD"), size=8)
       #title="Age Groups bifurcation", 
       #xlab="1 square = 1000 persons")

```





